mysql:
  name: mysql
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - /home/web/keycloak/mysql:/var/lib/mysql
  env_file:
     - ./common.env
keycloak:
  name: keycloak
  image: rxvallejoc/keycloak-server-mysql:1.6.1
  ports:
    - "8081:8081"
  links:
    - mysql
  env_file:
     - ./common.env
demo:
  name: demo
  image: rxvallejoc/wildfly-demo:8.2.1
  ports:
    - "8080:8080"
apache:
  name: apache
  image: rxvallejoc/apache-proxy
  ports:
    - "80:80"
  links:
    - keycloak
    - demo
