mysql:
  image: mysql 
  ports:
    - "3306:3306"
  volumes:
    - ~/dockerVolumes/mysql/keycloak:/var/lib/mysql
  env_file:
     - ./common.env
keycloak:
  image: jboss/keycloak-mysql
  environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
  ports:
    - "8181:8080"
  links:
    - mysql
  env_file:
     - ./common.env
